// ─────────────────────────────────────────────────────────────────────────────
//  services/language_service.dart
//  Multi-language support for VILAI app
//  Languages: Tamil, English, Hindi, Telugu, Kannada
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/material.dart';

// ── Language model ────────────────────────────────────────────────────────────
class AppLanguage {
  final String code;
  final String name;
  final String nativeName;
  final String flag;
  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
    required this.flag,
  });
}

// ── All supported languages ───────────────────────────────────────────────────
const List<AppLanguage> kLanguages = [
  AppLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳'),
  AppLanguage(code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧'),
  AppLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳'),
  AppLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳'),
  AppLanguage(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳'),
];

// ── Language service (singleton) ──────────────────────────────────────────────
class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._();
  static LanguageService get instance => _instance;
  LanguageService._();

  String _currentCode = 'ta'; // Default: Tamil
  String get currentCode => _currentCode;

  AppLanguage get currentLanguage =>
      kLanguages.firstWhere((l) => l.code == _currentCode,
          orElse: () => kLanguages.first);

  void setLanguage(String code) {
    if (_currentCode == code) return;
    _currentCode = code;
    notifyListeners();
  }

  // ── Get translated text ───────────────────────────────────────────────────
  String t(String key) {
    final translations = _translations[_currentCode];
    if (translations == null) return _translations['en']?[key] ?? key;
    return translations[key] ?? _translations['en']?[key] ?? key;
  }
}

// ── Global instance ───────────────────────────────────────────────────────────
final langService = LanguageService.instance;

// ── All translations ──────────────────────────────────────────────────────────
const Map<String, Map<String, String>> _translations = {
  // ════════════════════════════════════════════════════════
  //  TAMIL
  // ════════════════════════════════════════════════════════
  'ta': {
    // App
    'app_name': 'VILAI',
    'app_tagline': 'விலை • விவசாய உதவியாளர்',
    'live': '🟢 நேரலை',

    // Auth
    'welcome_back': 'வணக்கம்! மீண்டும் வாருங்கள் 👋',
    'login_subtitle': 'உங்கள் VILAI கணக்கில் நுழையுங்கள்',
    'register_title': 'VILAI-ல் இணையுங்கள்! 🌾',
    'register_subtitle': 'உங்கள் கணக்கை உருவாக்குங்கள்',
    'login': 'நுழைவு',
    'register': 'பதிவு',
    'phone': 'தொலைபேசி எண்',
    'password': 'கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல் உறுதிப்படுத்துக',
    'full_name': 'முழு பெயர்',
    'location': 'இடம்',
    'farm_size': 'நிலம் அளவு (விரும்பினால்)',
    'login_btn': 'VILAI-ல் நுழைக',
    'register_btn_farm': 'விவசாயியாக இணையுங்கள் 👨‍🌾',
    'register_btn_buy': 'வாங்குபவராக இணையுங்கள் 🍽️',
    'who_are_you': 'நீங்கள் யார்?',
    'farmer': 'விவசாயி',
    'buyer': 'வாங்குபவர்',
    'your_crops': 'உங்கள் பயிர்கள்:',
    'business_name': 'வணிக பெயர்',
    'business_type': 'வணிக வகை',
    'new_user': 'புதியவரா? பதிவு tab-ல் இணையுங்கள்!',

    // Home
    'greeting': 'வணக்கம்',
    'what_to_do': 'என்ன செய்யணும்?',
    'price_prediction': 'விலை கணிப்பு',
    'price_pred_sub': 'எப்போ விற்றால் max profit? Real ML + AI',
    'ai_chatbot': 'AI உரையாடல்',
    'ai_chatbot_sub': 'விவசாயம் பற்றி கேளுங்கள்',
    'markets': 'சந்தைகள் & விலைகள்',
    'markets_sub': 'நேரலை mandi விலைகள்',
    'govt_schemes': 'அரசு திட்டங்கள்',
    'govt_sub': 'PM-KISAN, பயிர் காப்பீடு & மேலும்!',
    'loans': 'வேளாண் கடன்',
    'loans_sub': 'KCC, NABARD, தங்க கடன் & மேலும்!',

    // Weather
    'weather_loading': 'வானிலை ஏற்றுகிறோம்...',
    'weather_error': 'வானிலை கிடைக்கவில்லை',
    'no_location': 'இடம் அமைக்கப்படவில்லை!',
    'no_location_msg': 'Profile-ல் உங்கள் நகரம் சேர்க்கவும்.',
    'good_weather': 'நல்ல நாள்! சந்தைக்கு போகலாம்!',
    'rain_warning': 'மழை எச்சரிக்கை!',
    'rain_msg': 'சந்தைக்கு போகாதீங்க — பயிர் பாதிக்கும்.',

    // Prediction
    'where_are_you': '1️⃣  நீங்கள் எங்கே?',
    'which_crop': '2️⃣  எந்த பயிர்?',
    'how_many_kg': '3️⃣  எத்தனை kg?',
    'days_since': '4️⃣  அறுவடை:',
    'days_ago': 'நாள் முன்பு',
    'sell_or_wait': 'எப்போ விற்றால் best?',
    'sell_today': '✅ இன்னைக்கே விக்கணும்!',
    'wait_days': 'நாள் காத்திரு!',
    'best_day': 'BEST DAY!',
    'today': 'இன்னைக்கு',
    'tomorrow': 'நாளை',
    'total': 'மொத்தம்',
    'real_data': 'உண்மையான அரசு தரவு',
    'ai_analysis': 'AI பகுப்பாய்வு',
    'just_harvested': '🌱 இன்னைக்கே அறுவடை',
    'days_left': 'நாள் மட்டுமே safe',

    // Chat
    'chat_title': 'AI விவசாய உதவியாளர்',
    'chat_subtitle': '🎤 குரல் • ⌨️ தட்டச்சு • தமிழ் & ஆங்கிலம்',
    'type_or_voice': 'தட்டச்சு அல்லது 🎤 குரலில் கேளுங்கள்...',
    'listening': '🎤 கேட்கிறேன்...',
    'speak_tamil': 'தமிழில் பேசுங்கள்...',
    'voice_on': '🔊 குரல் இயக்கம்',
    'voice_off': '🔇 குரல் நிறுத்தம்',

    // Markets
    'nearby_markets': 'அருகிலுள்ள சந்தைகள்',
    'best_market': 'சிறந்த சந்தை',
    'transport_cost': 'போக்குவரத்து செலவு',
    'net_profit': 'நிகர லாபம்',

    // Profile
    'profile': 'சுயவிவரம்',
    'logout': 'வெளியேறு',
    'sell_crop': 'பயிரை விற்கவும்',
    'find_crops': 'பயிர்களைக் கண்டுபிடி',
    'language': 'மொழி',
    'select_language': 'மொழி தேர்வு செய்யுங்கள்',

    // Common
    'loading': 'ஏற்றுகிறோம்...',
    'retry': 'மீண்டும் முயலுங்கள்',
    'back': 'திரும்பு',
    'save': 'சேமி',
    'cancel': 'ரத்து செய்',
    'close': 'மூடு',
    'search': 'தேடுங்கள்...',
    'per_kg': 'ஒரு கிலோவுக்கு',
    'per_quintal': 'ஒரு குவிண்டாலுக்கு',
    'apply_now': 'இப்போதே விண்ணப்பிக்கவும்',
  },

  // ════════════════════════════════════════════════════════
  //  ENGLISH
  // ════════════════════════════════════════════════════════
  'en': {
    'app_name': 'VILAI',
    'app_tagline': 'Price • Farmer Assistant',
    'live': '🟢 LIVE',
    'welcome_back': 'Welcome Back! 👋',
    'login_subtitle': 'Login to your VILAI account',
    'register_title': 'Join VILAI! 🌾',
    'register_subtitle': 'Create your account',
    'login': 'Login',
    'register': 'Register',
    'phone': 'Phone Number',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'full_name': 'Full Name',
    'location': 'Location',
    'farm_size': 'Farm Size (Optional)',
    'login_btn': 'Login to VILAI',
    'register_btn_farm': 'Join as Farmer 👨‍🌾',
    'register_btn_buy': 'Join as Buyer 🍽️',
    'who_are_you': 'Who are you?',
    'farmer': 'Farmer',
    'buyer': 'Buyer',
    'your_crops': 'Your Crops:',
    'business_name': 'Business Name',
    'business_type': 'Business Type',
    'new_user': 'New user? Join on Register tab!',
    'greeting': 'Welcome',
    'what_to_do': 'What would you like to do?',
    'price_prediction': 'Price Prediction',
    'price_pred_sub': 'When to sell for max profit? Real ML + AI',
    'ai_chatbot': 'AI Chatbot',
    'ai_chatbot_sub': 'Ask anything about farming',
    'markets': 'Markets & Prices',
    'markets_sub': 'Live mandi prices + weather',
    'govt_schemes': 'Govt Schemes',
    'govt_sub': 'PM-KISAN, Crop Insurance & more!',
    'loans': 'Farmer Loans',
    'loans_sub': 'KCC, NABARD, Gold Loan & more!',
    'weather_loading': 'Loading weather...',
    'weather_error': 'Weather unavailable',
    'no_location': 'Location not set!',
    'no_location_msg': 'Add your city in Profile.',
    'good_weather': 'Good day! Safe to go to market!',
    'rain_warning': 'Rain Warning!',
    'rain_msg': 'Avoid market — crops may get damaged.',
    'where_are_you': '1️⃣  Where are you?',
    'which_crop': '2️⃣  Which crop?',
    'how_many_kg': '3️⃣  How many kg?',
    'days_since': '4️⃣  Harvested:',
    'days_ago': 'days ago',
    'sell_or_wait': 'When to sell for best price?',
    'sell_today': '✅ SELL TODAY!',
    'wait_days': 'days to wait!',
    'best_day': 'BEST DAY!',
    'today': 'Today',
    'tomorrow': 'Tomorrow',
    'total': 'Total',
    'real_data': 'Real Government Data',
    'ai_analysis': 'AI Analysis',
    'just_harvested': '🌱 Just harvested today',
    'days_left': 'days left safe',
    'chat_title': 'AI Farmer Assistant',
    'chat_subtitle': '🎤 Voice • ⌨️ Type • Tamil & English',
    'type_or_voice': 'Type or 🎤 ask by voice...',
    'listening': '🎤 Listening...',
    'speak_tamil': 'Speak in Tamil...',
    'voice_on': '🔊 Voice ON',
    'voice_off': '🔇 Voice OFF',
    'nearby_markets': 'Nearby Markets',
    'best_market': 'Best Market',
    'transport_cost': 'Transport Cost',
    'net_profit': 'Net Profit',
    'profile': 'Profile',
    'logout': 'Logout',
    'sell_crop': 'Sell Your Crop',
    'find_crops': 'Find Fresh Crops',
    'language': 'Language',
    'select_language': 'Select Language',
    'loading': 'Loading...',
    'retry': 'Retry',
    'back': 'Back',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'search': 'Search...',
    'per_kg': 'per kg',
    'per_quintal': 'per quintal',
    'apply_now': 'Apply Now',
  },

  // ════════════════════════════════════════════════════════
  //  HINDI
  // ════════════════════════════════════════════════════════
  'hi': {
    'app_name': 'VILAI',
    'app_tagline': 'कीमत • किसान सहायक',
    'live': '🟢 लाइव',
    'welcome_back': 'वापस स्वागत है! 👋',
    'login_subtitle': 'अपने VILAI खाते में प्रवेश करें',
    'register_title': 'VILAI से जुड़ें! 🌾',
    'register_subtitle': 'अपना खाता बनाएं',
    'login': 'लॉगिन',
    'register': 'रजिस्टर',
    'phone': 'फोन नंबर',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'full_name': 'पूरा नाम',
    'location': 'स्थान',
    'farm_size': 'खेत का आकार (वैकल्पिक)',
    'login_btn': 'VILAI में लॉगिन करें',
    'register_btn_farm': 'किसान के रूप में जुड़ें 👨‍🌾',
    'register_btn_buy': 'खरीदार के रूप में जुड़ें 🍽️',
    'who_are_you': 'आप कौन हैं?',
    'farmer': 'किसान',
    'buyer': 'खरीदार',
    'your_crops': 'आपकी फसलें:',
    'business_name': 'व्यवसाय का नाम',
    'business_type': 'व्यवसाय का प्रकार',
    'new_user': 'नए उपयोगकर्ता? रजिस्टर टैब में जुड़ें!',
    'greeting': 'नमस्ते',
    'what_to_do': 'आप क्या करना चाहते हैं?',
    'price_prediction': 'मूल्य भविष्यवाणी',
    'price_pred_sub': 'अधिकतम लाभ के लिए कब बेचें? ML + AI',
    'ai_chatbot': 'AI चैटबॉट',
    'ai_chatbot_sub': 'खेती के बारे में कुछ भी पूछें',
    'markets': 'बाजार और कीमतें',
    'markets_sub': 'लाइव मंडी कीमतें + मौसम',
    'govt_schemes': 'सरकारी योजनाएं',
    'govt_sub': 'PM-KISAN, फसल बीमा & अधिक!',
    'loans': 'किसान ऋण',
    'loans_sub': 'KCC, NABARD, गोल्ड लोन & अधिक!',
    'weather_loading': 'मौसम लोड हो रहा है...',
    'weather_error': 'मौसम उपलब्ध नहीं',
    'no_location': 'स्थान सेट नहीं है!',
    'no_location_msg': 'प्रोफ़ाइल में अपना शहर जोड़ें।',
    'good_weather': 'अच्छा दिन! बाजार जाना सुरक्षित है!',
    'rain_warning': 'बारिश की चेतावनी!',
    'rain_msg': 'बाजार न जाएं — फसल को नुकसान हो सकता है।',
    'where_are_you': '1️⃣  आप कहाँ हैं?',
    'which_crop': '2️⃣  कौन सी फसल?',
    'how_many_kg': '3️⃣  कितने किलो?',
    'days_since': '4️⃣  कटाई:',
    'days_ago': 'दिन पहले',
    'sell_or_wait': 'सबसे अच्छे दाम के लिए कब बेचें?',
    'sell_today': '✅ आज ही बेचें!',
    'wait_days': 'दिन प्रतीक्षा करें!',
    'best_day': 'सबसे अच्छा दिन!',
    'today': 'आज',
    'tomorrow': 'कल',
    'total': 'कुल',
    'real_data': 'वास्तविक सरकारी डेटा',
    'ai_analysis': 'AI विश्लेषण',
    'just_harvested': '🌱 आज ही काटी गई',
    'days_left': 'दिन सुरक्षित',
    'chat_title': 'AI किसान सहायक',
    'chat_subtitle': '🎤 आवाज़ • ⌨️ टाइप करें',
    'type_or_voice': 'टाइप करें या 🎤 बोलें...',
    'listening': '🎤 सुन रहे हैं...',
    'speak_tamil': 'हिंदी में बोलें...',
    'voice_on': '🔊 आवाज़ चालू',
    'voice_off': '🔇 आवाज़ बंद',
    'nearby_markets': 'नजदीकी बाजार',
    'best_market': 'सबसे अच्छा बाजार',
    'transport_cost': 'परिवहन लागत',
    'net_profit': 'शुद्ध लाभ',
    'profile': 'प्रोफ़ाइल',
    'logout': 'लॉगआउट',
    'sell_crop': 'अपनी फसल बेचें',
    'find_crops': 'ताजी फसलें खोजें',
    'language': 'भाषा',
    'select_language': 'भाषा चुनें',
    'loading': 'लोड हो रहा है...',
    'retry': 'पुनः प्रयास करें',
    'back': 'वापस',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'close': 'बंद करें',
    'search': 'खोजें...',
    'per_kg': 'प्रति किलो',
    'per_quintal': 'प्रति क्विंटल',
    'apply_now': 'अभी आवेदन करें',
  },

  // ════════════════════════════════════════════════════════
  //  TELUGU
  // ════════════════════════════════════════════════════════
  'te': {
    'app_name': 'VILAI',
    'app_tagline': 'ధర • రైతు సహాయకుడు',
    'live': '🟢 లైవ్',
    'welcome_back': 'తిరిగి స్వాగతం! 👋',
    'login_subtitle': 'మీ VILAI ఖాతాలో లాగిన్ చేయండి',
    'register_title': 'VILAI లో చేరండి! 🌾',
    'register_subtitle': 'మీ ఖాతా తయారు చేయండి',
    'login': 'లాగిన్',
    'register': 'నమోదు',
    'phone': 'ఫోన్ నంబర్',
    'password': 'పాస్వర్డ్',
    'confirm_password': 'పాస్వర్డ్ నిర్ధారించండి',
    'full_name': 'పూర్తి పేరు',
    'location': 'స్థానం',
    'farm_size': 'పొలం పరిమాణం (ఐచ్ఛికం)',
    'login_btn': 'VILAI లో లాగిన్ చేయండి',
    'register_btn_farm': 'రైతుగా చేరండి 👨‍🌾',
    'register_btn_buy': 'కొనుగోలుదారుగా చేరండి 🍽️',
    'who_are_you': 'మీరు ఎవరు?',
    'farmer': 'రైతు',
    'buyer': 'కొనుగోలుదారు',
    'your_crops': 'మీ పంటలు:',
    'business_name': 'వ్యాపార పేరు',
    'business_type': 'వ్యాపార రకం',
    'new_user': 'కొత్త వినియోగదారా? నమోదు టాబ్‌లో చేరండి!',
    'greeting': 'నమస్కారం',
    'what_to_do': 'మీరు ఏమి చేయాలనుకుంటున్నారు?',
    'price_prediction': 'ధర అంచనా',
    'price_pred_sub': 'గరిష్ట లాభం కోసం ఎప్పుడు అమ్మాలి?',
    'ai_chatbot': 'AI చాట్',
    'ai_chatbot_sub': 'వ్యవసాయం గురించి అడగండి',
    'markets': 'మార్కెట్లు & ధరలు',
    'markets_sub': 'లైవ్ మండి ధరలు + వాతావరణం',
    'govt_schemes': 'ప్రభుత్వ పథకాలు',
    'govt_sub': 'PM-KISAN, పంట బీమా & మరిన్ని!',
    'loans': 'రైతు రుణాలు',
    'loans_sub': 'KCC, NABARD, బంగారు రుణం & మరిన్ని!',
    'weather_loading': 'వాతావరణం లోడ్ అవుతోంది...',
    'weather_error': 'వాతావరణం అందుబాటులో లేదు',
    'no_location': 'స్థానం సెట్ చేయబడలేదు!',
    'no_location_msg': 'ప్రొఫైల్‌లో మీ నగరం జోడించండి.',
    'good_weather': 'మంచి రోజు! మార్కెట్‌కు వెళ్ళవచ్చు!',
    'rain_warning': 'వర్షపు హెచ్చరిక!',
    'rain_msg': 'మార్కెట్‌కు వెళ్ళకండి — పంట దెబ్బతినవచ్చు.',
    'where_are_you': '1️⃣  మీరు ఎక్కడ ఉన్నారు?',
    'which_crop': '2️⃣  ఏ పంట?',
    'how_many_kg': '3️⃣  ఎన్ని కిలోలు?',
    'days_since': '4️⃣  కోత:',
    'days_ago': 'రోజుల క్రితం',
    'sell_or_wait': 'అత్యుత్తమ ధరకు ఎప్పుడు అమ్మాలి?',
    'sell_today': '✅ ఈరోజే అమ్మండి!',
    'wait_days': 'రోజులు వేచి ఉండండి!',
    'best_day': 'అత్యుత్తమ రోజు!',
    'today': 'ఈరోజు',
    'tomorrow': 'రేపు',
    'total': 'మొత్తం',
    'real_data': 'నిజమైన ప్రభుత్వ డేటా',
    'ai_analysis': 'AI విశ్లేషణ',
    'just_harvested': '🌱 ఈరోజే కోయబడింది',
    'days_left': 'రోజులు సురక్షితం',
    'chat_title': 'AI రైతు సహాయకుడు',
    'chat_subtitle': '🎤 వాయిస్ • ⌨️ టైప్ చేయండి',
    'type_or_voice': 'టైప్ చేయండి లేదా 🎤 అడగండి...',
    'listening': '🎤 వింటున్నాను...',
    'speak_tamil': 'తెలుగులో మాట్లాడండి...',
    'voice_on': '🔊 వాయిస్ ఆన్',
    'voice_off': '🔇 వాయిస్ ఆఫ్',
    'nearby_markets': 'సమీప మార్కెట్లు',
    'best_market': 'అత్యుత్తమ మార్కెట్',
    'transport_cost': 'రవాణా ఖర్చు',
    'net_profit': 'నికర లాభం',
    'profile': 'ప్రొఫైల్',
    'logout': 'లాగ్‌అవుట్',
    'sell_crop': 'మీ పంట అమ్మండి',
    'find_crops': 'తాజా పంటలు కనుగొనండి',
    'language': 'భాష',
    'select_language': 'భాష ఎంచుకోండి',
    'loading': 'లోడ్ అవుతోంది...',
    'retry': 'మళ్ళీ ప్రయత్నించండి',
    'back': 'వెనక్కి',
    'save': 'సేవ్ చేయి',
    'cancel': 'రద్దు చేయి',
    'close': 'మూసివేయి',
    'search': 'వెతకండి...',
    'per_kg': 'కిలోకు',
    'per_quintal': 'క్వింటాలుకు',
    'apply_now': 'ఇప్పుడే దరఖాస్తు చేయండి',
  },

  // ════════════════════════════════════════════════════════
  //  KANNADA
  // ════════════════════════════════════════════════════════
  'kn': {
    'app_name': 'VILAI',
    'app_tagline': 'ಬೆಲೆ • ರೈತ ಸಹಾಯಕ',
    'live': '🟢 ಲೈವ್',
    'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ! 👋',
    'login_subtitle': 'ನಿಮ್ಮ VILAI ಖಾತೆಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    'register_title': 'VILAI ಗೆ ಸೇರಿ! 🌾',
    'register_subtitle': 'ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ',
    'login': 'ಲಾಗಿನ್',
    'register': 'ನೋಂದಾಯಿಸಿ',
    'phone': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'password': 'ಪಾಸ್‌ವರ್ಡ್',
    'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
    'location': 'ಸ್ಥಳ',
    'farm_size': 'ಜಮೀನಿನ ಗಾತ್ರ (ಐಚ್ಛಿಕ)',
    'login_btn': 'VILAI ಗೆ ಲಾಗಿನ್ ಮಾಡಿ',
    'register_btn_farm': 'ರೈತರಾಗಿ ಸೇರಿ 👨‍🌾',
    'register_btn_buy': 'ಖರೀದಿದಾರರಾಗಿ ಸೇರಿ 🍽️',
    'who_are_you': 'ನೀವು ಯಾರು?',
    'farmer': 'ರೈತ',
    'buyer': 'ಖರೀದಿದಾರ',
    'your_crops': 'ನಿಮ್ಮ ಬೆಳೆಗಳು:',
    'business_name': 'ವ್ಯವಹಾರ ಹೆಸರು',
    'business_type': 'ವ್ಯವಹಾರ ಪ್ರಕಾರ',
    'new_user': 'ಹೊಸ ಬಳಕೆದಾರರಾ? ನೋಂದಾಯಿಸಿ ಟ್ಯಾಬ್‌ನಲ್ಲಿ ಸೇರಿ!',
    'greeting': 'ನಮಸ್ಕಾರ',
    'what_to_do': 'ನೀವೇನು ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
    'price_prediction': 'ಬೆಲೆ ಅಂದಾಜು',
    'price_pred_sub': 'ಗರಿಷ್ಠ ಲಾಭಕ್ಕಾಗಿ ಯಾವಾಗ ಮಾರಬೇಕು?',
    'ai_chatbot': 'AI ಚಾಟ್',
    'ai_chatbot_sub': 'ಕೃಷಿ ಬಗ್ಗೆ ಯಾವುದೇ ಪ್ರಶ್ನೆ ಕೇಳಿ',
    'markets': 'ಮಾರುಕಟ್ಟೆಗಳು & ಬೆಲೆಗಳು',
    'markets_sub': 'ಲೈವ್ ಮಂಡಿ ಬೆಲೆಗಳು + ಹವಾಮಾನ',
    'govt_schemes': 'ಸರಕಾರಿ ಯೋಜನೆಗಳು',
    'govt_sub': 'PM-KISAN, ಬೆಳೆ ವಿಮೆ & ಇನ್ನಷ್ಟು!',
    'loans': 'ರೈತ ಸಾಲಗಳು',
    'loans_sub': 'KCC, NABARD, ಚಿನ್ನದ ಸಾಲ & ಇನ್ನಷ್ಟು!',
    'weather_loading': 'ಹವಾಮಾನ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'weather_error': 'ಹವಾಮಾನ ಲಭ್ಯವಿಲ್ಲ',
    'no_location': 'ಸ್ಥಳ ಹೊಂದಿಸಲಾಗಿಲ್ಲ!',
    'no_location_msg': 'ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ನಿಮ್ಮ ನಗರ ಸೇರಿಸಿ.',
    'good_weather': 'ಒಳ್ಳೆಯ ದಿನ! ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗಬಹುದು!',
    'rain_warning': 'ಮಳೆ ಎಚ್ಚರಿಕೆ!',
    'rain_msg': 'ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗಬೇಡಿ — ಬೆಳೆ ಹಾನಿ ಆಗಬಹುದು.',
    'where_are_you': '1️⃣  ನೀವು ಎಲ್ಲಿದ್ದೀರಿ?',
    'which_crop': '2️⃣  ಯಾವ ಬೆಳೆ?',
    'how_many_kg': '3️⃣  ಎಷ್ಟು ಕಿಲೋ?',
    'days_since': '4️⃣  ಕಟಾವು:',
    'days_ago': 'ದಿನಗಳ ಹಿಂದೆ',
    'sell_or_wait': 'ಅತ್ಯುತ್ತಮ ಬೆಲೆಗೆ ಯಾವಾಗ ಮಾರಬೇಕು?',
    'sell_today': '✅ ಇಂದೇ ಮಾರಿ!',
    'wait_days': 'ದಿನ ಕಾಯಿರಿ!',
    'best_day': 'ಅತ್ಯುತ್ತಮ ದಿನ!',
    'today': 'ಇಂದು',
    'tomorrow': 'ನಾಳೆ',
    'total': 'ಒಟ್ಟು',
    'real_data': 'ನಿಜವಾದ ಸರಕಾರಿ ಡೇಟಾ',
    'ai_analysis': 'AI ವಿಶ್ಲೇಷಣೆ',
    'just_harvested': '🌱 ಇಂದೇ ಕಟಾವು',
    'days_left': 'ದಿನ ಸುರಕ್ಷಿತ',
    'chat_title': 'AI ರೈತ ಸಹಾಯಕ',
    'chat_subtitle': '🎤 ಧ್ವನಿ • ⌨️ ಟೈಪ್ ಮಾಡಿ',
    'type_or_voice': 'ಟೈಪ್ ಮಾಡಿ ಅಥವಾ 🎤 ಕೇಳಿ...',
    'listening': '🎤 ಕೇಳುತ್ತಿದ್ದೇನೆ...',
    'speak_tamil': 'ಕನ್ನಡದಲ್ಲಿ ಮಾತನಾಡಿ...',
    'voice_on': '🔊 ಧ್ವನಿ ಆನ್',
    'voice_off': '🔇 ಧ್ವನಿ ಆಫ್',
    'nearby_markets': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳು',
    'best_market': 'ಅತ್ಯುತ್ತಮ ಮಾರುಕಟ್ಟೆ',
    'transport_cost': 'ಸಾರಿಗೆ ವೆಚ್ಚ',
    'net_profit': 'ನಿವ್ವಳ ಲಾಭ',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'logout': 'ಲಾಗ್‌ಔಟ್',
    'sell_crop': 'ನಿಮ್ಮ ಬೆಳೆ ಮಾರಿ',
    'find_crops': 'ತಾಜಾ ಬೆಳೆ ಹುಡುಕಿ',
    'language': 'ಭಾಷೆ',
    'select_language': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'back': 'ಹಿಂದೆ',
    'save': 'ಉಳಿಸಿ',
    'cancel': 'ರದ್ದು ಮಾಡಿ',
    'close': 'ಮುಚ್ಚಿ',
    'search': 'ಹುಡುಕಿ...',
    'per_kg': 'ಪ್ರತಿ ಕಿಲೋ',
    'per_quintal': 'ಪ್ರತಿ ಕ್ವಿಂಟಾಲ್',
    'apply_now': 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
  },
};
