name: nilai_app
description: VILAI - Farmer Market Price Intelligence

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  permission_handler: ^11.0.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/farmer_hero.png
    - assets/app_logo.png
    - assets/register.png